name: 2fa
version: 'v1.0.0'
summary: Two-factor authentication agent
description: |
  2fa is a tool which provides two-factor authentication on the command line.
grade: stable
confinement: strict

parts:
  2fa:
    source: https://github.com/rsc/2fa.git
    source-tag: v1.0.0
    plugin: go
    go-importpath: github.com/rsc/2fa

apps:
  2fa:
    command: 2fa
